### ISSUE TITLE
QMS-011-SUB_ISSUE Error mocking AttendeeRepository (NullPointerException)

### ISSUE THREAD

**Issue by codexsameen** [samisnotinsane/qmsalsabooking#16]
In my JUnit `setUp` method, I have:
`Mockito.when(attendeeRepository.findBySurnameAndFirstName("Soares", "Carolina"))
                .thenReturn(carolina);`

Later, when I query the mock repository through the following method, I get an exception as detailed in the stacktrace below.

`Attendee found = attendeeService.findBySurnameAndFirstName(surname, firstName);`

**Stacktrace:**
`java.lang.NullPointerException
	at info.sameen.qmsalsabooking.integration.AttendeeServiceIntegrationTest.whenValidName_thenAttendeeShouldBeFound(AttendeeServiceIntegrationTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)`

**Comment by codexsameen** [comment]
This was being caused by a typo in the parameter `firstname`.
